### ISSUE TITLE
workshop paper of DSTC11

### ISSUE THREAD

**Issue by Chucy2020** [Jeiyoon/dstc11-track2#1]
Hi, did you receive any information about the workshop paper on DSTC11?

**Comment by Jeiyoon** [comment]
@Chucy2020 Not yet...

**Comment by Chucy2020** [comment]
Thanks, me too, this specified time is very inaccurate...

**Comment by Jeiyoon** [comment]
@Chucy2020 I hope the reviews come out soon...

**Comment by Chucy2020** [comment]
> @Chucy2020 I hope the reviews come out soon...

Hi, Did you receive the file about reviews? I didn't find it in the CMT system.
